# Generated by Django 2.2.5 on 2019-09-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0003_auto_20190908_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Note',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='NoteApp.Category'),
        ),
    ]
