# Generated by Django 2.2.5 on 2019-09-08 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0004_auto_20190908_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
