# Generated by Django 2.2.5 on 2019-09-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0005_note_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
