# Generated by Django 2.2.5 on 2019-11-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0009_auto_20190917_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
